# Copyright (c) 2025 Control Network. All rights reserved. Provided for evaluation only.
"""Markdown report: header + deterministic evidence (confidence chips) + AI narrative + disclaimer.

P0-3: the report is split into two unambiguous zones so a reader can never mistake AI text
for measured fact:
  - "Evidence -- deterministic" : facts pulled straight from collectors, confidence-chipped.
  - "Analysis -- AI context"    : the narrative (Claude/OpenAI-compatible/Ollama, or the
    deterministic template fallback when no model is configured/reachable).
"""
from __future__ import annotations
import datetime as dt
from .models import CompressedSignals

_CHIP = {"high": "🟢 high", "medium": "🟡 medium", "low": "🟠 low"}


def _humanize(key: str, val):
    """Render a raw fact value the way a human would read it (units, percentages). Shared by
    the markdown report and the `facts` SSE event so both agree byte-for-byte."""
    try:
        if isinstance(val, (int, float)) and str(key).endswith("_bytes"):
            v = float(val)
            for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
                if v < 1024 or unit == "TiB":
                    return f"{v:.1f} {unit}".replace(".0 ", " ")
                v /= 1024
        if isinstance(val, float) and ("utilization" in str(key) or str(key).endswith("_ratio")) and 0 <= val <= 1:
            return f"{val * 100:.0f}%"
    except Exception:
        pass
    return val


def humanized_facts(c: CompressedSignals) -> list[dict]:
    """List of {key, value, provenance} with values humanized, empties dropped. Used by the
    `facts` SSE event (P0-1) so the UI and the final markdown never disagree."""
    out = []
    for f in c.facts:
        val = _humanize(f["key"], f["value"])
        if val in (None, "", [], {}):
            continue
        out.append({"key": f["key"], "value": val, "provenance": f.get("provenance", "medium")})
    return out


def render_facts(c: CompressedSignals) -> str:
    lines = []
    for f in humanized_facts(c):
        lines.append(f"- **{f['key']}**: {f['value']}  ({_CHIP.get(f['provenance'], '🟡 medium')})")
    return "\n".join(lines) if lines else "- (no structured facts collected)"


def assemble(c: CompressedSignals, title: str, narrative: str) -> str:
    now = dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    trunc = "  ·  ⚠ context truncated" if c.meta.get("truncated") else ""
    return (
        f"## Incident Report: {c.alert_id}\n"
        f"**Alert:** {c.alert} ({title})  \n"
        f"**Service:** {c.service}  ·  **Namespace:** {c.namespace}  ·  **Cluster:** {c.cluster}  \n"
        f"**Severity:** {c.severity}  ·  **Generated:** {now}{trunc}\n"
        f"\n---\n"
        f"\n### 🟩 Evidence — deterministic\n"
        f"_Measured facts from collectors. No model involved. Confidence-chipped._\n\n"
        f"{render_facts(c)}\n"
        f"\n---\n"
        f"\n### 🤖 Analysis — AI context\n"
        f"_Narrative generated from the evidence above (or a deterministic template if no "
        f"model is available). Treat as a hypothesis, not a fact._\n\n"
        f"{narrative.strip()}\n"
        f"\n---\n"
        f"*Generated by Control Network · advisory only — not a substitute for human "
        f"judgment. Runs in-cluster, zero data retention.*\n"
    )
