# Copyright (c) 2025 Control Network. All rights reserved. Provided for evaluation only.
"""Extra incident scenarios — generated by Qwen (Qwen3.7), reviewed/normalized by Claude.

These flow through the SAME pipeline as the built-in scenarios. Qwen produced 4 complete
incidents (verbatim below) plus a 5th that streamed truncated, which Claude completed and
made schema-consistent. Kept in a separate file to keep provenance clear.
"""
from __future__ import annotations

EXTRA_SCENARIOS = [
    {
        "id": "oom-billing-api-payments-001",
        "alertname": "KubePodOOMKilled",
        "service": "billing-api",
        "namespace": "payments",
        "cluster": "eks-prod-use1",
        "severity": "critical",
        "summary": "billing-api in payments was OOMKilled (Java heap exhausted) 15 min after deploy.",
        "raw": {
            "metrics": {"container_memory_usage_bytes": 2147483648,
                         "container_memory_limit_bytes": 2147483648, "restarts": 3},
            "pod_describe": {"phase": "Running", "restart_count": 3,
                              "last_state": "OOMKilled", "node": "ip-10-0-5-12.ec2.internal"},
            "logs": ["2026-06-30T10:00:01Z INFO Starting billing-api...",
                      "2026-06-30T10:05:22Z ERROR java.lang.OutOfMemoryError: Java heap space",
                      "Killed"],
            "events": ["Normal Pulled Container image pulled",
                        "Warning OOMKilling Memory cgroup out of memory: Killed process"],
            "deployment": {"replicas": 3, "available_replicas": 2,
                            "last_deploy_sha": "a1b2c3d4e5f6", "minutes_before": 15, "author": "jdoe"},
        },
    },
    {
        "id": "crashloop-kafka-consumer-prod-002",
        "alertname": "KubePodCrashLooping",
        "service": "kafka-consumer",
        "namespace": "prod",
        "cluster": "eks-prod-use1",
        "severity": "warning",
        "summary": "kafka-consumer crash-looping (14 restarts) — broker connection refused.",
        "raw": {
            "metrics": {"restarts_total": 14, "uptime_seconds": 12},
            "pod_describe": {"phase": "Running", "restart_count": 14, "last_state": "Error",
                              "exit_code": 1, "node": "ip-10-0-8-22.ec2.internal"},
            "logs": ["2026-06-30T10:10:00Z INFO Connecting to kafka broker...",
                      "2026-06-30T10:10:05Z ERROR Connection refused: kafka-broker-0.kafka.svc.cluster.local:9092"],
            "events": ["Normal Scheduled Successfully assigned prod/kafka-consumer-5c8f9a7b3-m4n8p to ip-10-0-8-22",
                        "Warning BackOff Back-off restarting failed container"],
            "deployment": {"replicas": 2, "available_replicas": 1,
                            "last_deploy_sha": "f6e5d4c3b2a1", "minutes_before": 45, "author": "svc-deploy-bot"},
        },
    },
    {
        "id": "latency-search-service-prod-003",
        "alertname": "HighRequestLatency",
        "service": "search-service",
        "namespace": "prod",
        "cluster": "eks-prod-use1",
        "severity": "warning",
        "summary": "search-service p99 at 3.45s — CPU saturated, slow Elasticsearch queries.",
        "raw": {
            "metrics": {"http_request_duration_seconds_p99": 3.45,
                         "http_requests_total": 15000, "cpu_usage_cores": 1.8},
            "saturation": {"cpu_request_utilization": 0.92, "memory_request_utilization": 0.65,
                            "network_receive_bytes": 45000000},
            "logs": ["2026-06-30T10:15:00Z WARN Slow query detected: elasticsearch took 2800ms",
                      "2026-06-30T10:15:05Z WARN Thread pool queue full"],
            "deployment": {"replicas": 5, "available_replicas": 5,
                            "last_deploy_sha": "9876543210ab", "minutes_before": 120, "author": "asmith"},
        },
    },
    {
        "id": "pv-redis-prod-004",
        "alertname": "KubePersistentVolumeFillingUp",
        "service": "redis",
        "namespace": "prod",
        "cluster": "eks-prod-use1",
        "severity": "critical",
        "summary": "redis persistent volume 92% full — RDB snapshot failing, no space left.",
        "raw": {
            "metrics": {"kubelet_volume_stats_used_bytes": 92000000000,
                         "kubelet_volume_stats_capacity_bytes": 100000000000},
            "disk": {"filesystem": "/data", "used_percent": 92.0, "inodes_used_percent": 12.5},
            "pvc": {"name": "redis-data-redis-0", "storage_class": "gp3",
                     "capacity": "100Gi", "status": "Bound"},
            "events": ["Warning VolumeFailedCreate Failed to create volume",
                        "Normal SuccessfulAttachVolume AttachVolume.Attach succeeded"],
            "logs": ["2026-06-30T10:20:00Z WARN Disk usage is at 92%",
                      "2026-06-30T10:20:05Z ERROR Could not write RDB snapshot: No space left on device"],
        },
    },
    {
        # Qwen started this one; Claude completed the truncated tail.
        "id": "configerr-billing-api-payments-005",
        "alertname": "CreateContainerConfigError",
        "service": "billing-api",
        "namespace": "payments",
        "cluster": "eks-prod-use1",
        "severity": "critical",
        "summary": "billing-api stuck in CreateContainerConfigError — referenced ConfigMap missing.",
        "raw": {
            "pod_describe": {"phase": "Pending", "reason": "CreateContainerConfigError",
                              "restart_count": 0, "node": "ip-10-0-5-12.ec2.internal"},
            "events": ['Warning Failed configmap "billing-config" not found',
                        "Warning FailedMount MountVolume.SetUp failed for volume \"config\"",
                        "Normal Scheduled Successfully assigned payments/billing-api to ip-10-0-5-12"],
            "deployment": {"replicas": 3, "available_replicas": 2,
                            "last_deploy_sha": "c3d4e5f6a7b8", "minutes_before": 4, "author": "jdoe"},
        },
    },
]
